version: '3'
tasks:
  install:
    desc: Install all dependencies
    cmds:
      - cmd: cd backend && npm install
      - cmd: cd frontend && npm install

  dev:
    desc: Run development servers
    cmds:
      - cmd: cd backend && npm run dev
        silent: false
      - cmd: cd frontend && npm start
        silent: false

  docker:up:
    desc: Start Docker containers
    cmds:
      - cmd: docker-compose up -d

  docker:down:
    desc: Stop Docker containers
    cmds:
      - cmd: docker-compose down

  docker:logs:
    desc: View Docker logs
    cmds:
      - cmd: docker-compose logs -f

  seed:
    desc: Seed database with test data
    cmds:
      - cmd: cd backend && npm run seed

  build:
    desc: Build frontend
    cmds:
      - cmd: cd frontend && npm run build

  test:
    desc: Run tests
    cmds:
      - cmd: cd backend && npm test
      - cmd: cd frontend && npm test

  lint:
    desc: Lint code
    cmds:
      - cmd: cd backend && npx eslint .
      - cmd: cd frontend && npx eslint src

  format:
    desc: Format code with Prettier
    cmds:
      - cmd: cd backend && npx prettier --write .
      - cmd: cd frontend && npx prettier --write src
